/* eslint-disable no-undef */

// IMPORTANT: Workbox injectManifest requires self.__WB_MANIFEST to exist in this file.
// next-pwa will inject the precache list at build time.

importScripts("https://storage.googleapis.com/workbox-cdn/releases/6.5.4/workbox-sw.js");

if (self.workbox) {
  // Precache all assets generated by Next/next-pwa
  self.workbox.precaching.precacheAndRoute(self.__WB_MANIFEST);
}

self.addEventListener("install", () => {
  self.skipWaiting();
});

self.addEventListener("activate", (event) => {
  event.waitUntil(self.clients.claim());
});

// --------------------
// PUSH HANDLERS
// --------------------
self.addEventListener("push", (event) => {
  event.waitUntil((async () => {
    let data = {};
    try {
      data = event.data ? event.data.json() : {};
    } catch {
      data = {
        title: "Test",
        body: event.data ? event.data.text() : "Push received",
      };
    }

    // DEBUG: send message to all open tabs
    const allClients = await clients.matchAll({
      type: "window",
      includeUncontrolled: true,
    });

    for (const client of allClients) {
      client.postMessage({ type: "PUSH_RECEIVED", data });
    }

    await self.registration.showNotification(data.title || "New message", {
      body: data.body || "",
      data: data.data || {},
      requireInteraction: true,
    });
  })());
});

self.addEventListener("notificationclick", (event) => {
  event.notification.close();
  const url = event.notification.data?.url || "/";

  event.waitUntil((async () => {
    const allClients = await clients.matchAll({ type: "window", includeUncontrolled: true });

    for (const client of allClients) {
      if ("focus" in client) {
        await client.focus();
        if ("navigate" in client) await client.navigate(url);
        return;
      }
    }

    await clients.openWindow(url);
  })());
});
